# Generated by Django 5.0.6 on 2024-12-12 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sist_salud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('IS', 'IS'), ('FN', 'FN'), ('NO', 'NO')], default='NO', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_rut', models.CharField(max_length=9)),
                ('dv_rut', models.CharField(max_length=1)),
                ('primer_nombre', models.CharField(max_length=150)),
                ('segundo_nombre', models.CharField(blank=True, max_length=150)),
                ('apellido_paterno', models.CharField(max_length=150)),
                ('apellido_materno', models.CharField(max_length=150)),
                ('sist_salud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='polls.sist_salud')),
            ],
        ),
    ]
