# Generated by Django 5.0.6 on 2024-12-12 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='num_rut',
            field=models.CharField(max_length=8),
        ),
        migrations.CreateModel(
            name='Examenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_examen', models.CharField(max_length=255)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='documents/pdfs/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='polls.pacientes')),
            ],
        ),
    ]
