# Generated by Django 5.0.6 on 2024-12-12 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_pacientes_num_rut_examenes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Examenes',
            new_name='Examen',
        ),
        migrations.RenameModel(
            old_name='Pacientes',
            new_name='Paciente',
        ),
    ]
